# Generated by Django 4.1.6 on 2023-04-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin0', '0003_coupon'),
        ('user0', '0006_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin0.coupon', unique=True),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
