# Generated by Django 4.1.7 on 2023-04-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin0', '0004_addressdetails'),
        ('user0', '0008_order_payment_orderitem_order_payment_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin0.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
