# Generated by Django 4.1.6 on 2023-04-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user0', '0009_alter_cart_coupon_alter_cart_razorpay_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressDetails',
        ),
    ]
