# Generated by Django 4.1.6 on 2023-04-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin0', '0004_addressdetails'),
        ('user0', '0010_delete_addressdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin0.coupon'),
        ),
    ]
